# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mon-app .

      - name: Run container and perform a health check
        run: |
          echo "Starting container..."
          docker run -d --name test-container -p 8080:80 mon-app
          
          echo "Waiting for application to start..."
          sleep 5
          
          echo "Sending request to the application..."
          curl --fail http://localhost:8080 | grep "Hello, CI/CD World!" || exit 1
          
          echo "Cleaning up container..."
          docker stop test-container
          docker rm test-container
